// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9m_WgLPZ-0knVW5sOB5eaSD8y_QI8us4',
    appId: '1:134398556566:web:6294745e6a20a8f69f45b7',
    messagingSenderId: '134398556566',
    projectId: 'proect2525',
    authDomain: 'proect2525.firebaseapp.com',
    storageBucket: 'proect2525.appspot.com',
    measurementId: 'G-WYCBXXJMY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvMVygDa7Ol-LCo4r1Z41VoT0Y1GBncY8',
    appId: '1:134398556566:android:f687edc554356b839f45b7',
    messagingSenderId: '134398556566',
    projectId: 'proect2525',
    storageBucket: 'proect2525.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcSGLQVfbPeZdhN3oycKVhNfyBbRE6ynA',
    appId: '1:134398556566:ios:35935f39a3111cd39f45b7',
    messagingSenderId: '134398556566',
    projectId: 'proect2525',
    storageBucket: 'proect2525.appspot.com',
    iosClientId: '134398556566-0emth0bi8iq6cj93565birhqcnvqlm0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.dert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcSGLQVfbPeZdhN3oycKVhNfyBbRE6ynA',
    appId: '1:134398556566:ios:35935f39a3111cd39f45b7',
    messagingSenderId: '134398556566',
    projectId: 'proect2525',
    storageBucket: 'proect2525.appspot.com',
    iosClientId: '134398556566-0emth0bi8iq6cj93565birhqcnvqlm0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.dert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9m_WgLPZ-0knVW5sOB5eaSD8y_QI8us4',
    appId: '1:134398556566:web:10031f144f2597819f45b7',
    messagingSenderId: '134398556566',
    projectId: 'proect2525',
    authDomain: 'proect2525.firebaseapp.com',
    storageBucket: 'proect2525.appspot.com',
    measurementId: 'G-YS9WS7Q04Q',
  );
}
